= java core tech
:toc: left

== Java的基本程序设计结构

=== 注释
=== 数据类型
* 整形
* 浮点类型
* char类型
* Unicode和char类型
* boolean类型

=== 变量
static和final +
枚举类型

=== 字符串
StringBuilder避免每次产生一个新的字符串

=== 输入和输出
* Scanner（控制台、文件）
* PrintWriter
* 格式化输出
* 文件输入和输出，Paths、Path、Files、File

=== 控制流程
=== 大数值
* BigInteger
* BigDecimal

=== 数组
* 数组（Arrays工具类）

== 对象和类
=== 使用预定义类
* Date（某些方法废弃）和LocaleDate(无时分秒)

=== 用户自定义类
=== 静态域和静态方法
=== 方法参数
=== 对象构造
==== 重载
==== 默认域初始化
==== 无参数的构造器
=== 包
=== 类路径
=== 文档注释

== 继承
=== 类、超类和子类
* final修饰类或方法，阻止继承或覆盖

=== Object：所有类的超类
* equals方法判断两个对象是否具有相同的引用
* hashCoe是由对象导出的一个整数值
* toString方法返回表示对象值得字符串

=== 泛型数组列表
* ArrayList

=== 对象包装器与自动装箱
* 所有的基本类型都有一个与之对应的类

=== 参数数量可变的方法

=== 枚举类
* 用“==”比较两个枚举类型的值

=== 反射
==== Class类
* 获取Class类对象的方法
* 通过Class类对象获取实例的方法（newInstance）

==== 利用反射分析类的能力
* java.lang.reflect包中的三个类Field、Method、Constructor及Moodfier。

==== 在运行时使用反射分析对象
==== 使用反射编写泛型数组代码
* Arrays.copyOf扩充数组

==== 调用任意方法
* invoke方法
* 建议使用接口进行回调

== 接口、lambda表达式与内部类
=== 接口
* 在标准库中，成对出现接口和实用工具类
* 静态方法，使实现接口时，不再需要为实用工具方法提供伴随类
* Comparable和Comparator接口

=== lambda表达式
* 函数式接口
* 在java.util.function包中
* 方法引用
- object::instanceMethd
- Class::staticMethod
- Class::instanceMethod

=== 内部类
* 内部类
* 局部内部类
* 匿名内部类
* 静态内部类

=== 代理(没看懂)

== 异常、断言和日志
=== 异常分类
* 所有的异常都是由Throwable继承而来的，分为Error和Exception
* Exception分为RuntimeException（非受查（unchecked）异常）和其他（受查异常）

=== 捕获异常
* 一个方法必须声明所有可能抛出的受查异常
* 创建异常类：定义一个派生于Exception或者Exception子类的类
* 抛出原始异常？
* 带资源的try语句
* 分析堆栈轨迹元素

=== 使用断言
* 启用断言 java -enableassertions MyApp

=== 记录日志?
* 基本日志（全局）
* 高级日志
* 修改日志管理器配置
* 本地化（资源包？）
* 处理器（handler）
* 过滤器（Filter过滤想要显示的日志）
* 格式化器（好像不支持）

== 泛型程序设计
* 泛型和强制类型转换

=== 定义简单泛型类
....
public class Pair<T>{
    private T first;
    private T second;
    public Pair(){}
    pulic Pair(T first, T second){
        this.first = first;
        this.second = second;
    }
    ...
}
....
=== 泛型方法
....
class ArrayAlg{
    public static <T> T getMiddle(T ... a){
    }
}
....
=== 类型变量的限定
* 可以限定，只有实现了某些接口的类型才能实例化此泛型类，如对元素比较，限制只有实现了Comparable接口的类才能实例化泛型类
+
....
class ArrayAlg{
    public static <T extends Comparable> T minMax(T ... a){
    }
}
....

=== 泛型代码和虚拟机
虚拟机无泛型类型对象，所有对象都属于普通类，所以需要：

* 类型擦除
* 翻译泛型表达式（存取域值时进行强制类型转换）
* 翻译泛型方法
+
....
class DateInterval extends Pair<LocalDate>{
    public void setSecond(LocalDate second){
        if(second.compareTo(getFirst()) >= 0){
            super.setSecond(second);
        }
    }
    ...
}
....
这个继承的问题是不能实现多态，要生产一个桥方法才行
- 虚拟机中没有泛型，只有普通的类和方法
- 所有的类型参数都用它们的限定类型替换
- 桥方法被合成来保持多态
- 为保持类型安全性，必要时插入强制类型转换

* 调用遗留代码

下面两种情况会发出警告，但只要了解在做什么，可以消除警告（@SuppressWarnings("unchecked")）

- 泛型类对象作为参数传递给方法的非泛型参数
- 方法的非泛型返回值赋给泛型类对象

=== 约束与局限性
* 不能用基本类型实例化类型参数，有Pair<Double>，无Pair<double>
* 运行时类型查询只适用于原始类型
+
....
if(a instanceof Pair<String>)//Error
if(a instanceof Pair<T>)//Error
Pair<String> p = (Pair<String>)a;//warning
....
- getClass()总是返回原始类型
* 不能创建参数化类型的数组
+
....
Pair<String>[] table = new Pair<String>[10] //Error
Pair<String>[] table = (Pair<String>[])new Pair<?>[10] //Correct
....
* Varargs警告
+
向参数个数可变的方法传递泛型类型的实例会触发警告，对方法增加注解@SuppressWarning("unchecked")或者@SafeVarargs就可以了
* 不能实例化类型变量
+
....
public Pair(){first = new T(); second = new T();}   //Error
....
- 两种方法构造泛型对象
+
Java SE 8中的方法
+
....
Pair<String> p = Pair.makePair(String::new);
public static <T> Pair<T> makePair(Supplier<T> constr){
    return new Pair<>(constr.get(), constr.get());
}
....
+
传统的方法
+
....
Pair<String> p = Pair.makePair(String.class);
public static <T> Pair<T> makePair(Class<T> cl){
    try{
        return new Pair<>(cl.newInstance(), cl.newInstance());
    }catch(Exception ex){return null; }
}
....
* 不能构造泛型数组
+
....
public static <T extends Comparable> T[] minmax(T[] a){ T[] mm = new T[2]; }    //Error,永远构造Comparable[2]
....
+
Java SE 8
+
....
String[] ss = ArrayAlg.minmax(String[]::new, "Tom", "Dick", "Harry");
public static <T extends Comparable> T[] minmax(IntFunction<T[]> constr, T... a){
    T[] mm = constr.apply(2);
    ...
}
....
+
老式的反射方法
+
....
public static <T extends Comparable> T[] minmax(T... a){
    T[] mm = (T[])Array.newInstance(a.getClass().getComponentType(), 2);
    ...
}
....
* 泛型类的静态上下文中类型变量无效
+
不能在泛型类的静态域或方法中引用类型变量
* 不能抛出或铺货泛型类的实例
+
不能抛出也不能捕获泛型类对象，
+
....
public class Problem<T> extends Exception{/*...*/}  //Error--can't extend Throwable
public static <T extends Throwable> void doWork(T t) throws T{/*...*/}  //OK
....
* 可以消除对受查异常的检查
+
Java异常处理的基本原则是，必须为所有的受查异常提供一个处理器
+
以下代码可以消除这种限制
+
....
public abstract class Block{
    public abstract void body() throws Exception;
    public Thread toThread(){
        return new Thread(){
            public void run(){
                try{
                    body();
                }catch(Throwable t){
                    Block.<RuntimeException>throwAs(t);
                }
            }
        };
    }
    @SuppressWarning("unchecked")
    public static <T extends Throwable> void throwAs(Throwable e)throws T{
        throw(T) e;
    }
}
....
+
运行如下程序，会抛出异常，但不需要捕获
+
....
public clas Test{
    public static void main(String[] args){
        new Block(){
            public void body(){
                Scanner in = new Scanner(new File("ququx"), "UTF-8");
                while(in.hasNext()){
                    System.out.println(in.next());
                }
            }
        }.toThread().start();
    }
}
....
* 注意擦除后的冲突
+
在继承的类型中，子类的方法类型擦除后和父类的方法签名一致，造成冲突，如equals()方法
+
要想支持擦除的转换，就需要强行限制一个类或类型变量不能同时成为两个接口类型的子类，而这两个接口是同一接口的不同参数化
+
....
class Employee implements Comparable<Employee>{...}
class Manager extends Employee implements Comparable<Manager>{...}  /Error
....

=== 泛型类型的继承规则
* 数组可以赋值
+
....
Manager[] managerBuddies = { ceo, cfo };
Employee[] employeeBuddies = managerBuddies;
....
* 泛型类不可以这样
+
....
Pair<Manager> managerBuddies = new Pair<>( ceo, cfo );
Pair<Employee> employeeBuddies = managerBuddies;    //illegal
....
* ArrayList<T>实现List<T>接口，因此，一个ArrayList<Manager>可以被转换为一个List<Manager>；一个ArrayList<Manager>不是一个ArrayList<Employee>或List<Employee>

=== 通配符类型
* 通配符概念
- Pair<? extends Employss>，作为方法参数时，可以作为Pair<Employee>和Pair<Manager>的通用类型
- 有限定的通配符，可以实现安全的访问器方法和不安全的更改器方法
* 通配符的超类型限定
- ? super Manager
- 带有超类型限定的通配符可以向泛型对象写入，带有子类型限定的通配符可以从泛型对象读取
- public static <T extends Comparable<? super T>> T min(T[] a)
* 无限定通配符
- Pair<?>，返回值只能赋给一个Object
+
测试一个pair是否包含一个null引用
+
....
public static boolean hasNulls(Pair<?> p){
    return p.getFirst() == null || p.getSecond() == null;
}
....
* 通配符捕获
- 交换成对元素的方法
+
....
public static <T> void swapHelper(Pair<T> p){
    T t = p.getFirst();
    p.setFirst(p.getSecond());
    p.setSecond(T);
}
public static void swap(Pair<?> p){
    swapHelper(p);
}
....

=== 反射和泛型
* 泛型Class类
+
....
T newInstance()
T cast(Object obj)
T[] getEnumConstants()
Class<? super T> getSuperClass()
Constructor<T> getConstructor(Class ... parameterTypes)
Constructor<T> getDeclareConstructor(Class ... parameterTypes)
....
???????

== 集合
=== Java集合框架
* 将集合的接口与实现分离
* Collection接口
+
....
public interface Collection<E>{
    boolean add(E element);
    Iterator<E> iterator();
    ...
}
....
* 迭代器
+
....
public interface Iterator<E>{
    E next();
    boolean hasNext();
    void remove();
    default void forEachRemaininng(Consumer<? super E> action);
}
....
- for each循环可以与任何实现了Iterable接口的对象一起工作
+
....
public interface Iterable<E>{
    Iterator<E> iterator();
    ...
}
....
* 泛型实用方法
+
Java类库提供了一个类AbstractCollection
* 集合框架中的接口
- Iterable<-Collection
+
List、Set<-SortedSet<-NavigableSet<-TreeSet、Queue<-Deque
- Map<-SortedMap<-NavigableMap<-TreeMap
- Iterator<-ListIterator
- RandomAccess

=== 具体的集合
* 链表
- Java中，所有链表都是双向链接的
- 集合类库提供了子接口ListIterator
+
....
interface ListIterator<E> extends Iterator<E>{
    void add(E element);
    E previous();
    boolean hasPrevious();
    ...
}
....
* 数组列表
- ArrayList封装了一个动态再分配的对象数组
* 散列集
- HashSet
* 树集
- TreeSet是有序集合
- 使用树集，元素必须实现Comparable接口或者在构造树集时必须提供一个Comparator
- NavigableSet<Item> sortByDescription = new TreeSet<>(Comparator.comparing(Item::getDescription));
* 队列与双端队列
- Queue<E>：添加（add、offer）、删除（remove、poll）、获取（element、peek）元素的方法，分别返回异常和null
- Deque<E>：同上，但换成首尾，即分别First和Last
- ArrayDeque<E>
* 优先级队列（PriorityQueue）
- 使用堆（heap）的数据结构
- 典型示例是任务调度

=== 映射
* 基本映射操作
- 两个通用的实现：HashMap和TreeMap
- get方法可以用getOrDefault方法替换，值不存在时返回默认值
- put方法返回键对应的上一个值
- Map.forEach(k, v)方法遍历
* 更新映射项
- 键不存在时，获得键值会返回null，对null值操作会返回异常，可以先用putIfAbsent和merge方法处理
* 映射视图
- Set<K> keySet()
- Collection<V> values()
- Set<Map.Entry<K, V>> entrySet()
* 弱散列映射
+
WeakHashMap
* 链接散列集与映射
- LinkedHashSet
- LinkedHashMap
+
用访问顺序而不是插入顺序对映射条目进行迭代 +
可用于实现高速缓存的“最近最少使用”原则 +
+
....
Map<K, V> cache = new LinkedHashMap<>(128, 0.75F, true){
    protected boolean removeEldestEntry(Map.Entry<K, V> eldest){
        return size() > 100;
    }
}();
....
* 枚举集与映射
- EnumSet是一个枚举类型元素集的实现
....
enum Weekday {MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY};
EnumSet<Weekday> always = EnumSet.allOf(Weekday.class)
EnumSet<Weekday> never = EnumSet.noneOf(Weekday.class)
EnumSet<Weekday> workday = EnumSet.range(Weekday.MONDAY, Weekday.FRIDAY)
EnumSet<Weekday> mwf = EnumSet.range(Weekday.MONDAY, Weekday.WEDNSDAY, Weekday.FRIDAY)
....
- EnumMap是一个键类型为枚举类型的映射
+
....
EnumMap<Weekday, Employee> personInCharge = new EnumMap<>(Weekday.class)
....
* 标识散列映射
- IdentityHashMap

=== 视图与包装器
*  轻量级集合包装器
+
....
List<Card> cardList（返回的视图对象） = Arrays.asList(cardDeck(数组))
List<String> names = Arrays.asList("Amy", "Bob", "Carl");
调用了
Collections.nCopies(n, anObject);
....
* 子范围
+
List的subList方法 +
SortedSet的subSet、headSet、tailSet方法 +
SortedMap的subMap、headMap、tailMap方法
* 不可修改的视图
+
....
Collections.unmodifiableCollection
Collections.unmodifiableList
Collections.unmodifiableSet
Collections.unmodifiableSortedSet
Collections.unmodifiableNavigableSet
Collections.unmodifiableMap
Collections.unmodifiableSortedMap
Collections.unmodifiableNavigableMap
....
* 同步视图
- 可以线程安全的访问
+
Map<String, Employee> map = Collections.synchronizedMap(new HashMap<String, Employee>());
* 受查视图
- 受查视图是用来对泛型类型发生问题时提供调试支持
+
....
ArrayList<String> strings = new ArrayList<>()
List<String. safeStrings = Collections.checkedList(strings, String.class)
ArrayList rawList = safeStrings;
rawList.add(new Date()); //checked list throws a ClassCastException
....

=== 算法
* 排序与混排
- 主要是Collections的方法
* 二分查找
+
....
Collections.binarySearch(...)
....
* 简单算法
* 批操作
- 对视图应用批操作
* 集合与数组的转换
+
....
String[] values = ...;
HashSet<String> staff = new HashSet<>(Arrays.asList(values));
Object[] values = staff.toArray();
String[] values = (String[])staff.toArray();    //Error
String[] values = staff.toArray(new String[0]);
....

=== 遗留的集合
* HashTable类
- 方法是同步的
* 枚举
* 属性映射
* 栈
* 位集
- 查找素数

== 图形程序设计
== 事件处理
== Swing用户界面组件
== 部署Java应用程序
=== JAR文件
* 创建JAR文件
+
....
jar options File1 File2
eg:
jar cvf JARFileName File1 File2
....
* 清单文件
- 每个JAR文件包含一个用于描述归档特征的清单文件（manifest）-MANIFEST.MF，位于META-INF子目录中
- 使用jar命令创建、更新清单文件
* 可执行JAR文件
- jar cvfe MyProgram.jar com.mycompany.mypkg.MainAppClass files to add  //e选项指定程序的入口点
* 资源
+
....
URL url = ResourceTest.class.getResource("about.gif");
Image img = new ImageIcon(url).getImage();

InputStream stream = ResourceTest.class.getResourceAsStream("about.txt");
Scanner in = new Scanner(stream, "UTF-8");
....
* 密封
+
在清单文件中增加一节
+
....
Sealed: true/false
....

=== 应用首选项的存储
* 属性映射
- 实现属性映射的Java类名为Properties
+
....
InputStream inputStream = new BufferedInputStream(new FileInputStream("E:\\project\\java-core-tech\\src\\main\\resources\\a.properties"));
Properties properties = new Properties();
properties.load(inputStream);
Iterator<String> iterator = properties.stringPropertyNames().iterator();
while(iterator.hasNext()){
    String key = iterator.next();
    System.out.println(properties.getProperty(key));
}
inputStream.close();
FileOutputStream fileOutputStream = new FileOutputStream("b.properties", true);
properties.store(fileOutputStream, "Add new");
fileOutputStream.close();
....
* 首选项API([red]#待完成#)

=== 服务加载器
* 提供一个接口
* 实现接口中的方法
* 把类名增加到META-INF/services目录下的一个UTF-8编码文件中，文件名必须与完全限定类名一致，用点号分隔
* 调用
+
....
public static ServiceLoader<Cipher> cipherLoader = ServiceLoader.load(Cipher.class);
....
+
之后通过对cipherLoader使用iterator找到要使用的服务

=== applet（[red]#待完成#）

== 并发
=== 什么是线程
* 使用线程给其他任务提供机会
+
....
public interface Runnable{
    void run();
}
Runnable r = () -> { task code };
Thread t = new Thread();
t.start();
....

=== 中断线程
+
....
public class App implements Runnable
{
    public static void main( String[] args )throws Exception {
        Thread thread = new Thread(new App(), "first");
        thread.start();Thread.sleep(1000);
        thread.interrupt(); //1、中断标志置位；2、在线程阻塞时，抛出异常
        System.out.println("main end");
    }
    @Override
    public void run(){
        while(true){
            if(Thread.currentThread().isInterrupted()){ //检查中断位；静态方法interrupted会重置中断标志位false
                System.out.println("Yes,I am interruted,but I am still running");
                return;
            }else{
                System.out.println("not yet interrupted");
            }
        }
    }
}
....

=== 线程状态
可调用getState()方法获得线程状态

* 新创建线程（New）
* 可运行线程（Runnable）
* 被阻塞线程（Blocked）和等待线程（Waiting、Timed waiting）
* 被终止的线程（Terminated）

=== 线程属性
* 线程优先级
- void setPriority(int newPriority)
- static int MIN_PRIORITY
- static int NORM_PRIORITY
- static int MAX_PRIORITY
- static void yield()
* 守护线程
- void setDaemon(boolean isDaemon)
* 未捕获异常处理器（？）
- 异常被传递到一个用于未捕获异常的处理器
- 该处理器属于一个实现Thread.UncaughtExceptionHandler接口的类，这个类只有一个方法，void uncaughtException(Thread t, Throwable e)
- 可以用setUncaughtExceptionHandler或Thread的静态方法setDefaultUncaughtExceptionHandler为线程安装处理器
- ThreadGroup（？）

=== 同步
* 竞争条件的一个例子
+
....
public class Bank {
    private final double[] accounts;
    public Bank(int n, double initialBalance){
        accounts = new double[n];
        Arrays.fill(accounts, initialBalance);
    }
    public void transfer(int from, int to, double amount){
        if(accounts[from]<amount) return;
        System.out.println(Thread.currentThread());
        accounts[from] -= amount;
        System.out.printf(" %10.2f from %d to %d", amount, from, to);
        accounts[to] += amount;
        System.out.printf("Total Balance: %10.2f%n", getTotalBalance());
    }
    public double getTotalBalance(){
        double sum = 0;
        for(double a : accounts){
            sum += a;
        }
        return sum;
    }
    public int size(){
        return accounts.length;
    }
}
....
* 竞争条件详解
* 锁对象
- synchronized
- ReentrantLock
+
....
public class Bank {
    private Lock bankLock = new ReentrantLock()
    private final double[] accounts;
    ...
    public void transfer(int from, int to, double amount){
        bankLock.lock();
        try{
            ...
        }finally{
            bankLock.unlock();
        }
    }
    ...
}
....
* 条件对象
- 使用一个条件对象来管理那些已经获得了一个锁但是却不能做有用工作的线程
- 不满足条件时调用Condition类对象的await方法阻塞线程，并释放锁
- 条件满足时，调用Condition类对象的sinalAll方法唤醒阻塞线程
+
....
public class Bank {
    private final double[] accounts;
    private Lock bankLock;
    private Condition sufficientFunds;

    public Bank(int n, double initialBalance){
        accounts = new double[n];
        Arrays.fill(accounts, initialBalance);
        bankLock = new ReentrantLock();
        sufficientFunds = bankLock.newCondition();
    }
    public void transfer(int from, int to, double amount)throws InterruptedException{
        bankLock.lock();
        try {
            while (accounts[from] < amount){
                sufficientFunds.await();
            };
            ...
            sufficientFunds.signalAll();
        }finally {
            bankLock.unlock();
        }
    }
    ...
}
....
* synchronized关键字
- 每一个对象有一个内部锁，并且该锁有一个内部条件
+
....
public class Bank {
    ...
    public synchronized void transfer(int from, int to, double amount)throws InterruptedException{
        while (accounts[from] < amount){
            wait();
        };
        ...
        notifyAll();
    }
    ...
}
....
* 同步阻塞
- 每一个java对象有一个锁
+
....
synchronized(obj){
    critical section
}
....
* 监视器概念
- 监视器时只包含私有域的类
- 每个监视器类的对象有一个相关的锁
- 使用该所对所有的方法进行加锁
- 该锁可以有任意多个相关条件
- Java设计者以不是很精确的方式采用了监视器概念
* Volatile域
- volatile关键字为实例域的同步访问提供了一种免锁机制
- 除非使用锁或volatile修饰符，否则无法从多个线程安全地读取一个域
- 对共享变量除了赋值外无其他操作，可以将其声明为volatile
* final变量
- 域声明为final，多线程可以安全地访问
* 原子性
- java.util.concurrent.atomic的学习
* 死锁
* 线程局部变量
- 使用ThreadLocal辅助类为各个线程提供各自的实例
- 会调用混乱示例
+
....
public static final SimpleDateFormat dataFormat = new SimpleDateFormat("yyyy-MM-dd");
String dateStamp = dateFormat.format(new Date());
....
- 正确的调用
+
....
public static final ThreadLocal<SimpleDateFormat> dateFormat = ThreadLocal.withInitial(()->new SimpleDateFormat("yyyy-MM-dd"));
String dateStamp = dateFormat.get().format(new Date());
....
- java.util.Random随机数生成
+
....
int random = ThreadLocalRandom.current().netInt(upperBound);
....
* 锁测试与超时
- 谨慎的获取锁，可以立即返回，可以超时返回，可以被中断
+
....
if(mylock.tryLock(1000, TimeUnit.MILISECONDS)){
    ....
}else{
    ....
}
....
* 读写锁
+
....
private ReentrantReadWriteLock rwl = new ReentrantReadWriteLock();
//获取毒读锁和写锁
private Lock readLock = rwl.readLock();
private Lock writeLock = rwl.writeLock();
//对获取方法加读锁
public double getTotalBalance(){
    readLock.lock();
    try{...}
    finally{ readLock.unlock(); }
}
//对所有修改方法加写锁
public void transfer(...){
    writeLock.lock();
    try{...}
    finally{ writeLock.unlock(); }
}
....
* 为什么弃用stop和suspend方法

=== 阻塞队列
* 阻塞队列方法
- add、remove、element方法操作会返回异常
- offer、poll、peek不会返回异常
* java.util.concurrent中的阻塞队列
- LinkedBlockingQueue
- ArrayBlockingQueue
- PriorityBlockingQueue
- DelayQueue包含实现Delayed接口的对象
+
....
interface Delayed extends Comparable<Delayed>{
    long getDelay(TimeUnit unit);
}
....
- LinkedTransferQueue实现了TransferQueue，允许生产者线程等待

=== 线程安全的集合（[red]#未完成#）
* 高效的映射、集和队列
- java.util.concurrent包提供了映射、有序集和队列的高效实现：ConcurrentHashMap、ConcurrentSkipListMap、ConcurrentSkipListSet和ConcurrentLinkedQueue
* 映射条目的原子更新

=== Callable与Future
- Callable
+
....
public interface Callable<V>{
    V call() throws Exception;
}
....
- Future
+
....
public interface Future<V>{
    V get() throws ...;
    V get(long timeout, TimeUnit unit) throws ...;
    void cancel(boolean mayInterrupt);
    boolean isCancelled();
    boolean isDone();
}
....
- FutureTask包装器
+
....
Callable<Integer> myComputation = ...;
FutureTask<Integer> task = new FutureTask<Integer>(myComputation);
Thread t = new Thread(task); //it's a Runnable
t.start();
...
Integer result = task.get();    //it's a Futue
....

=== 执行器

执行器（Executor）类有许多静态工厂方法用来构建线程池

* 线程池
- 这3个方法返回实现了ExecutorService接口的ThreadPoolExecutor类的对象
+
....
newCachedThreadPool
newFixedThreadPool
newSingleThreadExecutor
....
- 下述方法将一个Runnable对象或Callable对象提交给ExecutorService
+
....
Future<?> submit(Runnable  task);
Future<T> submit(Runnable task, T result);
Future<T> submit(Callable<T> task);
....
* 预定执行（Scheduled Execution）
- 下述方法返回实现了ScheduledExecutorService接口的对象
+
....
newScheduledThreadPool
newSingleThreadScheduledExecutor
....
* 控制任务组
- invokeAny方法提交所有对象到一个Callable对象的集合中，并返回某个已经完成了的任务的结果
- invokeAll方法提交所有对象到一个Callable对象的集合中，并返回一个Future对象的列表，代表所有任务的解决方案
+
....
List<Callable<T>> tasks = ...;
List<Future<T>> results = executor.invokeAll(tasks);
for(Future<T> result : results){
    processFurther(result.get());
}
....
- ExecutorCompletionService
+
....
ExecutorCompletionService<T> service = new ExecutorCompletionService(executor);
for(Callable<T> task : tasks){
    service.submit(task);
}
for(int i=0; i<tasks.size(); i++){
    processFurther(service.take().get());
}
....
* Fork-Join框架
- 可分别计算的子任务
+
....
public static void main( String[] args ){
        final int SIZE = 10000000;
        double[] numbers = new double[SIZE];
        for(int i=0; i<SIZE; i++){
            numbers[i] = Math.random();
        }

    }
    class Counter extends RecursiveTask<Integer>{
        public static final int THRESHOLD = 1000;
        private double[] values;
        private int from;
        private int to;
        private DoublePredicate filter;

        public Counter(double[] values, int from, int to, DoublePredicate filter){
            this.values = values;
            this.from = from;
            this.to = to;
            this.filter = filter;
        }

        @Override
        protected Integer compute() {
            if(to-from<THRESHOLD){
                int count = 0;
                for(int i=from; i<to; i++){
                    if(filter.test(values[i])){
                        count++;
                    }
                }
                return count;
            }else{
                int mid = (from+to)/2;
                Counter first = new Counter(values, from, mid, filter);
                Counter second = new Counter(values, mid, to, filter);
                invoke(first, second);
                return first.join()+second.join();
            }
        }
    }
....