= java core tech
:toc: left

== Java的基本程序设计结构

=== 注释
=== 数据类型
* 整形
* 浮点类型
* char类型
* Unicode和char类型
* boolean类型

=== 变量
static和final +
枚举类型

=== 字符串
StringBuilder避免每次产生一个新的字符串

=== 输入和输出
* Scanner（控制台、文件）
* PrintWriter
* 格式化输出
* 文件输入和输出，Paths、Path、Files、File

=== 控制流程
=== 大数值
* BigInteger
* BigDecimal

=== 数组
* 数组（Arrays工具类）

== 对象和类
=== 使用预定义类
* Date（某些方法废弃）和LocaleDate(无时分秒)

=== 用户自定义类
=== 静态域和静态方法
=== 方法参数
=== 对象构造
==== 重载
==== 默认域初始化
==== 无参数的构造器
=== 包
=== 类路径
=== 文档注释

== 继承
=== 类、超类和子类
* final修饰类或方法，阻止继承或覆盖

=== Object：所有类的超类
* equals方法判断两个对象是否具有相同的引用
* hashCoe是由对象导出的一个整数值
* toString方法返回表示对象值得字符串

=== 泛型数组列表
* ArrayList

=== 对象包装器与自动装箱
* 所有的基本类型都有一个与之对应的类

=== 参数数量可变的方法

=== 枚举类
* 用“==”比较两个枚举类型的值

=== 反射
==== Class类
* 获取Class类对象的方法
* 通过Class类对象获取实例的方法（newInstance）

==== 利用反射分析类的能力
* java.lang.reflect包中的三个类Field、Method、Constructor及Moodfier。

==== 在运行时使用反射分析对象
==== 使用反射编写泛型数组代码
* Arrays.copyOf扩充数组

==== 调用任意方法
* invoke方法
* 建议使用接口进行回调

== 接口、lambda表达式与内部类
=== 接口
* 在标准库中，成对出现接口和实用工具类
* 静态方法，使实现接口时，不再需要为实用工具方法提供伴随类
* Comparable和Comparator接口

=== lambda表达式
* 函数式接口
* 在java.util.function包中
* 方法引用
- object::instanceMethd
- Class::staticMethod
- Class::instanceMethod

=== 内部类
* 内部类
* 局部内部类
* 匿名内部类
* 静态内部类

=== 代理(没看懂)

== 异常、断言和日志
=== 异常分类
* 所有的异常都是由Throwable继承而来的，分为Error和Exception
* Exception分为RuntimeException（非受查（unchecked）异常）和其他（受查异常）

=== 捕获异常
* 一个方法必须声明所有可能抛出的受查异常
* 创建异常类：定义一个派生于Exception或者Exception子类的类
* 抛出原始异常？
* 带资源的try语句
* 分析堆栈轨迹元素

=== 使用断言
* 启用断言 java -enableassertions MyApp

=== 记录日志?
* 基本日志（全局）
* 高级日志
* 修改日志管理器配置
* 本地化（资源包？）
* 处理器（handler）
* 过滤器（Filter过滤想要显示的日志）
* 格式化器（好像不支持）

== 泛型程序设计
* 泛型和强制类型转换

=== 定义简单泛型类
....
public class Pair<T>{
    private T first;
    private T second;
    public Pair(){}
    pulic Pair(T first, T second){
        this.first = first;
        this.second = second;
    }
    ...
}
....
=== 泛型方法
....
class ArrayAlg{
    public static <T> T getMiddle(T ... a){
    }
}
....
=== 类型变量的限定
* 可以限定，只有实现了某些接口的类型才能实例化此泛型类，如对元素比较，限制只有实现了Comparable接口的类才能实例化泛型类
+
....
class ArrayAlg{
    public static <T extends Comparable> T minMax(T ... a){
    }
}
....

=== 泛型代码和虚拟机
虚拟机无泛型类型对象，所有对象都属于普通类，所以需要：

* 类型擦除
* 翻译泛型表达式（存取域值时进行强制类型转换）
* 翻译泛型方法
+
....
class DateInterval extends Pair<LocalDate>{
    public void setSecond(LocalDate second){
        if(second.compareTo(getFirst()) >= 0){
            super.setSecond(second);
        }
    }
    ...
}
....
这个继承的问题是不能实现多态，要生产一个桥方法才行
- 虚拟机中没有泛型，只有普通的类和方法
- 所有的类型参数都用它们的限定类型替换
- 桥方法被合成来保持多态
- 为保持类型安全性，必要时插入强制类型转换

* 调用遗留代码

下面两种情况会发出警告，但只要了解在做什么，可以消除警告（@SuppressWarnings("unchecked")）

- 泛型类对象作为参数传递给方法的非泛型参数
- 方法的非泛型返回值赋给泛型类对象

=== 约束与局限性
* 不能用基本类型实例化类型参数，有Pair<Double>，无Pair<double>
* 运行时类型查询只适用于原始类型
+
....
if(a instanceof Pair<String>)//Error
if(a instanceof Pair<T>)//Error
Pair<String> p = (Pair<String>)a;//warning
....
- getClass()总是返回原始类型
* 不能创建参数化类型的数组
+
....
Pair<String>[] table = new Pair<String>[10] //Error
Pair<String>[] table = (Pair<String>[])new Pair<?>[10] //Correct
....
* Varargs警告
+
向参数个数可变的方法传递泛型类型的实例会触发警告，对方法增加注解@SuppressWarning("unchecked")或者@SafeVarargs就可以了
* 不能实例化类型变量
+
....
public Pair(){first = new T(); second = new T();}   //Error
....
- 两种方法构造泛型对象
+
Java SE 8中的方法
+
....
Pair<String> p = Pair.makePair(String::new);
public static <T> Pair<T> makePair(Supplier<T> constr){
    return new Pair<>(constr.get(), constr.get());
}
....
+
传统的方法
+
....
Pair<String> p = Pair.makePair(String.class);
public static <T> Pair<T> makePair(Class<T> cl){
    try{
        return new Pair<>(cl.newInstance(), cl.newInstance());
    }catch(Exception ex){return null; }
}
....
* 不能构造泛型数组
+
....
public static <T extends Comparable> T[] minmax(T[] a){ T[] mm = new T[2]; }    //Error,永远构造Comparable[2]
....
+
Java SE 8
+
....
String[] ss = ArrayAlg.minmax(String[]::new, "Tom", "Dick", "Harry");
public static <T extends Comparable> T[] minmax(IntFunction<T[]> constr, T... a){
    T[] mm = constr.apply(2);
    ...
}
....
+
老式的反射方法
+
....
public static <T extends Comparable> T[] minmax(T... a){
    T[] mm = (T[])Array.newInstance(a.getClass().getComponentType(), 2);
    ...
}
....
* 泛型类的静态上下文中类型变量无效
+
不能在泛型类的静态域或方法中引用类型变量
* 不能抛出或铺货泛型类的实例
+
不能抛出也不能捕获泛型类对象，
+
....
public class Problem<T> extends Exception{/*...*/}  //Error--can't extend Throwable
public static <T extends Throwable> void doWork(T t) throws T{/*...*/}  //OK
....
* 可以消除对受查异常的检查
+
Java异常处理的基本原则是，必须为所有的受查异常提供一个处理器
+
以下代码可以消除这种限制
+
....
public abstract class Block{
    public abstract void body() throws Exception;
    public Thread toThread(){
        return new Thread(){
            public void run(){
                try{
                    body();
                }catch(Throwable t){
                    Block.<RuntimeException>throwAs(t);
                }
            }
        };
    }
    @SuppressWarning("unchecked")
    public static <T extends Throwable> void throwAs(Throwable e)throws T{
        throw(T) e;
    }
}
....
+
运行如下程序，会抛出异常，但不需要捕获
+
....
public clas Test{
    public static void main(String[] args){
        new Block(){
            public void body(){
                Scanner in = new Scanner(new File("ququx"), "UTF-8");
                while(in.hasNext()){
                    System.out.println(in.next());
                }
            }
        }.toThread().start();
    }
}
....
* 注意擦除后的冲突
+
在继承的类型中，子类的方法类型擦除后和父类的方法签名一致，造成冲突，如equals()方法
+
要想支持擦除的转换，就需要强行限制一个类或类型变量不能同时成为两个接口类型的子类，而这两个接口是同一接口的不同参数化
+
....
class Employee implements Comparable<Employee>{...}
class Manager extends Employee implements Comparable<Manager>{...}  /Error
....

=== 泛型类型的继承规则
* 数组可以赋值
+
....
Manager[] managerBuddies = { ceo, cfo };
Employee[] employeeBuddies = managerBuddies;
....
* 泛型类不可以这样
+
....
Pair<Manager> managerBuddies = new Pair<>( ceo, cfo );
Pair<Employee> employeeBuddies = managerBuddies;    //illegal
....
* ArrayList<T>实现List<T>接口，因此，一个ArrayList<Manager>可以被转换为一个List<Manager>；一个ArrayList<Manager>不是一个ArrayList<Employee>或List<Employee>

=== 通配符类型
* 通配符概念
- Pair<? extends Employss>，作为方法参数时，可以作为Pair<Employee>和Pair<Manager>的通用类型
- 有限定的通配符，可以实现安全的访问器方法和不安全的更改器方法
* 通配符的超类型限定
- ? super Manager
- 带有超类型限定的通配符可以向泛型对象写入，带有子类型限定的通配符可以从泛型对象读取
- public static <T extends Comparable<? super T>> T min(T[] a)
* 无限定通配符
- Pair<?>，返回值只能赋给一个Object
+
测试一个pair是否包含一个null引用
+
....
public static boolean hasNulls(Pair<?> p){
    return p.getFirst() == null || p.getSecond() == null;
}
....
* 通配符捕获
- 交换成对元素的方法
+
....
public static <T> void swapHelper(Pair<T> p){
    T t = p.getFirst();
    p.setFirst(p.getSecond());
    p.setSecond(T);
}
public static void swap(Pair<?> p){
    swapHelper(p);
}
....

=== 反射和泛型
* 泛型Class类
+
....
T newInstance()
T cast(Object obj)
T[] getEnumConstants()
Class<? super T> getSuperClass()
Constructor<T> getConstructor(Class ... parameterTypes)
Constructor<T> getDeclareConstructor(Class ... parameterTypes)
....
???????

== 集合