=== 不使用XML
使用servlet作为控制器
....
@WebServlet(name="", urlPatterns={"", ""})
public class xxx extends HttpServlet{
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        RequestDispatcher rd = req.getRequestDispatcher("xxx");
        rd.forward(req, resp);
        or
        resp.sendRedirect("http://www.baidu.com");
    }
}
....

使用filter作为控制器
....
@WebFilter(filterName="", urlPatterns={""})
public class xxx extends Filter{
    @Override
    public void init(FilterConfig filterConfig) throws ServletException{
    }
    @Override
    public void destroy(FilterConfig filterConfig) throws ServletException{
    }
    @Override
    public void doFilter(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    }
}
....
继承自Controller
....
public class xxxController implements Controller{
    @Override
    public ModelAndView handleRequest(HttpServletRequest req, HttpServletResponse resp) throws Exception{
        return new ModelAndView("");
    }
}
....

=== 使用XML配置
==== 配置web.xml

==== 配置xxx-servlet.xml
....
<bean name="/input-product" class="com.chinaums.open.controller.ServletCOntroller" />
....
=== 视图解析
==== 配置xxx-servlet.xml
....
<bean id="viewResolver" class="org.springframework.web.servlet.view.InternalResourceViewResolver">
    <property name="prefix" value="/WEB-INF/jsp" />
    <property name="suffix" value=".jsp" />
</bean>
....

== 注解
@Controller
<context:component-scan base-package="" />
@RequestMapping(value="", method={,})

== 可以在请求处理方法中出现的参数类型
+
....
javax.servlet.ServletRequest或javax.servlet.http.HttpServletRequest
javax.servlet.ServletResponse或javax.servlet.http.HttpServletResponse
javax.servlet.http.HttpSession
org.springframework.web.context.request.WebRequest或org.springframework.web.context.request.NativeWebRequest
java.util.Locale
java.io.InputStream或java.io.Reader
java.io.OutputStream或java.io.Writer
java.security.Principle
HttpEntity<?>parameters
java.util.Map/org.springframework.ui.Model(@ModelAttribute注解会把相应参数放到Ｍｏｄｅｌ中)
org.springframework.ui.ModelMap
org.springframework.web.servlet.mvc.support.RedirectAttribute
org.springframework.validation.Errors
org.springframework.validation.BindingResult
org.springframework.web.bind.support.SessionStatus
org.springframework.web.util.UriComponentsBuilder
@PathVariable、@MatrixVariable、@RequestParam、@RequestHeader、@RequestBody、@RequestPart
....

== 请求处理方法可以返回的类型对象
ModelAndView、Model、包含模型的属性的Map、View、代表逻辑视图名的String、void、提供对Servlet的访问，以响应HTTP头部和内容HttpEntity或ResponseEntity对象、Callable、DeferredResult、其他任意类型，Spring将其视作输出给View的对象模型
