=== 不使用XML
使用servlet作为控制器
....
@WebServlet(name="", urlPatterns={"", ""})
public class xxx extends HttpServlet{
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
        RequestDispatcher rd = req.getRequestDispatcher("xxx");
        rd.forward(req, resp);
        or
        resp.sendRedirect("http://www.baidu.com");
    }
}
....

使用filter作为控制器
....
@WebFilter(filterName="", urlPatterns={""})
public class xxx extends Filter{
    @Override
    public void init(FilterConfig filterConfig) throws ServletException{
    }
    @Override
    public void destroy(FilterConfig filterConfig) throws ServletException{
    }
    @Override
    public void doFilter(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    }
}
....
继承自Controller
....
public class xxxController implements Controller{
    @Override
    public ModelAndView handleRequest(HttpServletRequest req, HttpServletResponse resp) throws Exception{
        return new ModelAndView("");
    }
}
....

=== 使用XML配置
==== 配置web.xml

==== 配置xxx-servlet.xml
....
<bean name="/input-product" class="com.chinaums.open.controller.ServletCOntroller" />
....
=== 视图解析
==== 配置xxx-servlet.xml
....
<bean id="viewResolver" class="org.springframework.web.servlet.view.InternalResourceViewResolver">
    <property name="prefix" value="/WEB-INF/jsp" />
    <property name="suffix" value=".jsp" />
</bean>
....
